services:
  mongodb:
    image: mongo:latest
    container_name: go-graph-mongodb
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

  
